name: Free Ubuntu VPS (6 Hours)

on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH + Tunnel
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-server

          sudo systemctl enable ssh
          sudo systemctl start ssh

          echo "runner:Su@12345" | sudo chpasswd
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

          # localhost.run tunnel
          ssh -o StrictHostKeyChecking=no -R 80:localhost:22 nokey@localhost.run > tunnel.log 2>&1 &
          sleep 15

          echo "=============================================="
          echo "SSH INFO:"
          cat tunnel.log
          echo ""
          echo "Username : runner"
          echo "Password : Su@12345"
          echo "=============================================="

          sudo apt-get install -y nmap hydra sqlmap nikto john hashcat netcat-traditional whois dnsutils

      - name: Keep Alive (6 hours)
        run: sleep 6h
